const HttpStatus = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

const Messages = {
  WRONG_PASSWORD: "Passwords do not match",
  EMAIL_EXISTS: "User with this email already exists",
  INVALID_REF_CODE: "Invalid referral code",
  FAILED_TO_SEND_OTP: "Failed to send OTP. Please try again.",
  INVALID_OTP: "Invalid OTP. Please try again.",
  INVALID_OTP_FORMAT:'Invalid OTP format',
  OTP_NOT_MATCHING:"OTP not matching",
  SERVER_ERROR: "An error occurred. Please try again.",
  EMAIL_NOT_FOUND: "Email not found in session",
  OTP_RESEND_SUCCESS: "OTP Resent Successfully",
  FAILED_TO_RESEND: "Failed to resend OTP. Please try again.",
  USER_NOT_FOUND: "User not found",
  USER_BLOCKED:"User is blocked by admin",
  INCORRECT_PASSWORD:"Incorrect Password",
  LOGIN_FAILED:"login failed.Please try again later",
  UPLOAD_IMAGE:" Please upload an image",
  UNAUTHORIZED_LOGIN:"Unauthorized: Please log in first.",
  BLOCKED_CART:"Your account is blocked. You cannot access the cart.",
  INVALID_PRODUCTID:"Invalid product ID.",
  PRODUCT_NOT_FOUND:"Product not found.",
  PRODUCT_CART:"This product cannot be added to the cart.",
  PRODUCT_OUT_OF_STOCK:"Product is out of stock.",
  PRODUCT_STOCK_INSUFFIENT:"Cannot add more items; product stock is insufficient.",
  PRODUCT_ADDED_TO_CART:"Product added to cart!",
  CART_NOT_FOUND:"Cart not found",
  ITEM_NOT_FOUND_CART:"Item not found in cart",
  MAX_QTY_EXCEEDED:"Maximum quantity for one product exceeded",
  MIN_QTY_REACHED:"Minimum quantity reached",
  ITEM_REMOVED_CART:"Item removed successfully",
  CART_EMPTY:"Cart is empty",
  ITEMS_CART_NO_LONGER_AVAILABLE:"Some items in your cart are no longer available. Please remove them to proceed.",
  ITEMS_CATEGORY_NO_LONGER_AVAILABLE:"Some items in your cart belong to unavailable categories. Please remove them to proceed.",
  CART_QTY:"Some items in your cart exceed available stock. Please adjust quantities.",
  CART_VALID:"Cart is valid for checkout",
  COUPON_ALREADY_APPLIED:'Coupon already applied',
  INVALID_COUPON:'Invalid or expired coupon',
  NO_COUPON_TO_REMOVE:'No coupon to remove',
  INVALID_AMOUNT:'Invalid amount',
  ADDRESS_NOT_FOUND:"Address not found",
  INVALID_ORDERID:"Invalid order ID",
  ORDER_NOT_FOUND:"Order not found",
  ORDER_NOT_FAILED:"Order is not in a failed state",
  ITEMS_UNAVAILABLE:"Some items in your order are unavailable, out of stock, or belong to unavailable categories.",
  CART_RESTORED:"Cart restored for retrying payment",
  FAILED_ORDERS:"Failed orders cannot be cancelled. Please retry payment.",
  ORDER_CANNOT_BE_CANCELLED:"Order cannot be cancelled.",
  ITEM_CANNOT_BE_CANCELLED:"Item cannot be cancelled.",
  INVALID_CARTID:"Item cannot be cancelled.",
  INVOICE_NOT_AVAILABLE:'Invoice not available for cancelled or failed orders.',
  RETURN_REASON:"Return reason is mandatory",
  DELIVERED_ITEMS_RETURNED:"Only delivered items can be returned",
  PENDING_RETURN_REQUEST:"Item is already returned or has a pending return request",
  INVALID_NAME:'Invalid name format. Must be at least 3 letters.',
  INVALID_PHONE:'Invalid phone number. Must be 10 digits.',
  FIELDS_REQUIRED:"All fields are required",
  PASSWORDS_NOT_MATCH:"New passwords do not match",
  INCORRECT_CURRENT_PASSWORD:"Incorrect current password",
  PASSWORD_UPDATED_SUCCESS:"Password updated successfully",
  EMAIL_REQUIRED:"Email is required",
  INVALID_EMAIL_FORMAT:"Invalid email format",
  OTP_SUCCESS:"OTP sent successfully"



  
};

module.exports = {
  HttpStatus,
  Messages,
};
